### ISSUE TITLE
最新版Tale应用主题后报错

### ISSUE THREAD

**Issue by dzy0302** [otale/theme_indigo#1]
显示主题应用成功
但主页空白
已重启一遍Tale
错误信息：
com.blade.exception.TemplateException: jetbrick.template.runtime.InterpretException: object is null

template: themes/theme_indigo-master/index.html: 10,31
-------------------------------------------------------------------------------
  8: <div class="container body-wrap">
  9:     <ul class="post-list">
 10:         #for(article : articles.list)
                                    ^ -- here
 11:         <li class="post-list-item fade">
 12:             <article id="post-data-sync-in-vue-single-page-application" class="article-card article-type-post"
-------------------------------------------------------------------------------

	at com.blade.mvc.view.template.JetbrickTemplateEngine.render(JetbrickTemplateEngine.java:105)
	at com.blade.mvc.http.HttpResponse.render(HttpResponse.java:200)
	at com.blade.mvc.http.Response.render(Response.java:272)
	at com.blade.mvc.handler.RequestInvoker.handle(RequestInvoker.java:92)
	at com.blade.mvc.handler.RequestInvoker.routeHandle(RequestInvoker.java:55)
	at com.blade.server.netty.HttpServerHandler.channelRead0(HttpServerHandler.java:108)
	at com.blade.server.netty.HttpServerHandler.channelRead0(HttpServerHandler.java:34)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.handler.codec.http.HttpServerExpectContinueHandler.channelRead(HttpServerExpectContinueHandler.java:95)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: jetbrick.template.runtime.InterpretException: object is null

template: themes/theme_indigo-master/index.html: 10,31
-------------------------------------------------------------------------------
  8: <div class="container body-wrap">
  9:     <ul class="post-list">
 10:         #for(article : articles.list)
                                    ^ -- here
 11:         <li class="post-list-item fade">
 12:             <article id="post-data-sync-in-vue-single-page-application" class="article-card article-type-post"
-------------------------------------------------------------------------------

	at jetbrick.template.parser.ast.AstInvokeField.execute(AstInvokeField.java:52)
	at jetbrick.template.parser.ast.AstDirectiveFor.execute(AstDirectiveFor.java:42)
	at jetbrick.template.parser.ast.AstStatementList.execute(AstStatementList.java:212)
	at jetbrick.template.parser.ast.AstTemplate.execute(AstTemplate.java:37)
	at jetbrick.template.JetTemplateImpl.doInterpret(JetTemplateImpl.java:160)
	at jetbrick.template.JetTemplateImpl.render(JetTemplateImpl.java:141)
	at com.blade.mvc.view.template.JetbrickTemplateEngine.render(JetbrickTemplateEngine.java:103)
	... 43 more

**Comment by dzy0302** [comment]
日常催更(｀・ω・´)

**Comment by hellokaton** [comment]
Ｏ(≧口≦)Ｏ 抱歉，这个是未完成版本，最近在做另一个blog主题。
